// flow-typed signature: a4fe81154a262b19e1bfd9e04e089cf8
// flow-typed version: <<STUB>>/tooltip.js_v^1.3.3/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tooltip.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tooltip.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tooltip.js/dist/esm/tooltip' {
  declare module.exports: any;
}

declare module 'tooltip.js/dist/esm/tooltip.min' {
  declare module.exports: any;
}

declare module 'tooltip.js/dist/tooltip' {
  declare module.exports: any;
}

declare module 'tooltip.js/dist/tooltip.min' {
  declare module.exports: any;
}

declare module 'tooltip.js/dist/umd/tooltip' {
  declare module.exports: any;
}

declare module 'tooltip.js/dist/umd/tooltip.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tooltip.js/dist/esm/tooltip.js' {
  declare module.exports: $Exports<'tooltip.js/dist/esm/tooltip'>;
}
declare module 'tooltip.js/dist/esm/tooltip.min.js' {
  declare module.exports: $Exports<'tooltip.js/dist/esm/tooltip.min'>;
}
declare module 'tooltip.js/dist/tooltip.js' {
  declare module.exports: $Exports<'tooltip.js/dist/tooltip'>;
}
declare module 'tooltip.js/dist/tooltip.min.js' {
  declare module.exports: $Exports<'tooltip.js/dist/tooltip.min'>;
}
declare module 'tooltip.js/dist/umd/tooltip.js' {
  declare module.exports: $Exports<'tooltip.js/dist/umd/tooltip'>;
}
declare module 'tooltip.js/dist/umd/tooltip.min.js' {
  declare module.exports: $Exports<'tooltip.js/dist/umd/tooltip.min'>;
}
